# Servicios/contenedores del sistema
services:
  # Contenedor backend FastAPI
  backend:
    build: ./backend            # Construir imagen usando Dockerfile local
    container_name: backend     # Nombre del contenedor
    ports:                      # Mapeo de puertos  
      - "${BACKEND_PORT}:8000"
    networks:
      - grand_safe_net

# Redes
networks:
  grand_safe_net:
