"""
@file op_status.py

"""

OP_STATUS_OK = 0

OP_STATUS_USER_NOT_FOUND = 1
OP_STATUS_INVALID_PASSWORD = 2

OP_STATUS_INVALID_TOKEN = 10

OP_STATUS_REQUEST_NOT_FOUND = 20
OP_STATUS_INVALID_REQUEST_STATUS = 21

OP_STATUS_PERMISSION_DENIED = 30